version: '3.8'

services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
    volumes:
      - ./Base_de_datos/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5454:5432"
    networks:
      - app-tier
    container_name: db
    restart: always

  webapp:
    restart: always
    build: ./Aplicacion_datos
    volumes:
      - ./Aplicacion_datos:/usr/src/app
    ports:
      - 4000:5000
    networks:
      - app-tier
    container_name: webapp

networks:
  app-tier:
    driver: bridge



