# Dockerfile for webapp

# Usa la imagen base apropiada
FROM python:3.12

# Instala las dependencias del sistema necesarias
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de la aplicación
COPY ./ /usr/src/app

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Comando para iniciar la aplicación (ajústalo según sea necesario)
CMD ["python", "app.py"]
