FROM python:3
COPY . /usr/src/app
COPY requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
#RUN pip install -r requirements.txt
CMD ["python", "app.py"]
#RUN apk add --no-cache python3-dev \
 #   && pip3 install --upgrade pip

#COPY ./requirements.txt .


# Instala las herramientas de compilación necesarias
#RUN apt-get update && apt-get install -y \
 #   build-essential \
  #  gfortran \
   # libatlas-base-dev \
    #&& rm -rf /var/lib/apt/lists/*

# Instala las dependencias de Python


# Copia todo el contenido del directorio actual al contenedor
#COPY . .

# Expone el puerto 5000 para la aplicación Flask
#EXPOSE 5000

# Especifica el comando por defecto para ejecutar la aplicación
