# Usa la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres:latest

# Opcional: Define las variables de entorno para configurar la base de datos
ENV POSTGRES_DB=melidb
ENV POSTGRES_USER=meli
ENV POSTGRES_PASSWORD=p4ssw0rd

# Opcional: Copia un archivo de inicialización de la base de datos (si es necesario)
# COPY init.sql /docker-entrypoint-initdb.d/

# Opcional: Expone el puerto de PostgreSQL (por defecto es 5432)
EXPOSE 5432
